Aufgabe_5_2a.o: Aufgabe_5_2a.cpp Aufgabe_5_2a.h Helper.h
Aufgabe_5_2b.o: Aufgabe_5_2b.cpp Aufgabe_5_2b.h Helper.h
Aufgabe_5_2c.o: Aufgabe_5_2c.cpp Aufgabe_5_2c.h Helper.h
Beispiel_5_1.o: Beispiel_5_1.cpp Beispiel_5_1.h Helper.h
Beispiel_5_2.o: Beispiel_5_2.cpp Beispiel_5_2.h Helper.h
Helper.o: Helper.cpp Helper.h
main.o: main.cpp Beispiel_5_1.h Beispiel_5_2.h Aufgabe_5_2a.h \
 Aufgabe_5_2b.h Aufgabe_5_2c.h
